services:
  - type: web
    runtime: static
    name: studio-erica-silva
    repo: https://github.com/Lopesloro/studio-erica-silva
    branch: main
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=604800
